version: 0.2

phases:
  build:
    commands:
      - |
        aws s3 sync . s3://koppe-0101\
        --exclude ".git/*" \
        --exclude "buildspec.yml" \
        --exclude "README.md"

artifacts:
  files:
    - '**/*'
